#!/bin/bash
wp media import /data/media/photos/profile.jpg --title="Profile Picture" --alt="Purple Crochet Profile Picture" --allow-root
wp media import /data/media/photos/post_3786850348217600174.jpg --title="Post 3786850348217600174" --caption="" --alt="Instagram Post" --allow-root
wp media import /data/media/photos/post_3789798629818223666.jpg --title="Post 3789798629818223666" --caption="Recent Crochet Scarf Order 🫶💞 DM FOR INQUIRIES ❤️  #crochet #crochetscarf #crochetredscarf" --alt="Instagram Post" --allow-root
wp media import /data/media/videos/video_3789798629818223666.mp4 --title="Video 3789798629818223666" --caption="Recent Crochet Scarf Order 🫶💞 DM FOR INQUIRIES ❤️  #crochet #crochetscarf #crochetredscarf" --allow-root
wp media import /data/media/photos/post_3583031019896589526.jpg --title="Post 3583031019896589526" --caption="Oversized Crochet Daisy Cardigan ( colour customisation available) 💌  Note : These are handmade cardigans it will take 3-4 weeks to make them and deliver.   No COD❌ No bargain ❌ Only prepaid orders accepted   Standard shipping charges 60/-  .  Phone charms , crochet granny square, crochet keychains , crochet scarf, beads , crochet , crochet cardigan , yarn , wool , crochet pattern , crochet pullover , crochet pouches, crochet tutorial, crochet tutorial for beginners , makeup pouch  #crochet #crochetkeychain #yarn #crochetpattern  #crochetersofinstagram #keychains #smallbusinessindia #handmade #handmadewithlove #fashion #supportlocal #fyp #explore #trending #womeninbusiness #instagram  #giftsforher #giftsforhim #reelsinstagram #india #crochetpaw #crochetpawcoaster #crochetbag #crochetscarf #crochettop #crochetcardigan #crochetpullover #crochetsunflower #crochetgrannysquare" --alt="Instagram Post" --allow-root
wp media import /data/media/videos/video_3583031019896589526.mp4 --title="Video 3583031019896589526" --caption="Oversized Crochet Daisy Cardigan ( colour customisation available) 💌  Note : These are handmade cardigans it will take 3-4 weeks to make them and deliver.   No COD❌ No bargain ❌ Only prepaid orders accepted   Standard shipping charges 60/-  .  Phone charms , crochet granny square, crochet keychains , crochet scarf, beads , crochet , crochet cardigan , yarn , wool , crochet pattern , crochet pullover , crochet pouches, crochet tutorial, crochet tutorial for beginners , makeup pouch  #crochet #crochetkeychain #yarn #crochetpattern  #crochetersofinstagram #keychains #smallbusinessindia #handmade #handmadewithlove #fashion #supportlocal #fyp #explore #trending #womeninbusiness #instagram  #giftsforher #giftsforhim #reelsinstagram #india #crochetpaw #crochetpawcoaster #crochetbag #crochetscarf #crochettop #crochetcardigan #crochetpullover #crochetsunflower #crochetgrannysquare" --allow-root
wp media import /data/media/photos/post_3911138402881692180.jpg --title="Post 3911138402881692180" --caption="Let’s pack a crochet order💫💝 DM To Purchase ✨  #crochet #crochetorder #amigurimi #crochetkeychains #crochetbow   [crochet butterfly, crochet order, crochet hairclips, crochet bow, crochet plushie keychains, crochet tulip, crochet tulip flower, crochet clover, crochet rose, crochet flowers, crochet plushie, crochet sunflower, crochet daisy, crochet spiderman, crochet penguin, crochet turtle, crochet scarf, crochet blanket, crochet minion, crochet pouch]" --alt="Instagram Post" --allow-root
wp media import /data/media/videos/video_3911138402881692180.mp4 --title="Video 3911138402881692180" --caption="Let’s pack a crochet order💫💝 DM To Purchase ✨  #crochet #crochetorder #amigurimi #crochetkeychains #crochetbow   [crochet butterfly, crochet order, crochet hairclips, crochet bow, crochet plushie keychains, crochet tulip, crochet tulip flower, crochet clover, crochet rose, crochet flowers, crochet plushie, crochet sunflower, crochet daisy, crochet spiderman, crochet penguin, crochet turtle, crochet scarf, crochet blanket, crochet minion, crochet pouch]" --allow-root
wp media import /data/media/photos/post_3911111365206993493.jpg --title="Post 3911111365206993493" --caption="Crochet Tulip Flower 🌷✨🤌 DM To Order❤️  #crochet #crochettulip #amigurimi #crochetflower #crochetbusiness   [crochet butterfly, crochet tulip, crochet tulip flower, crochet clover, crochet rose, crochet flowers, crochet plushie, crochet sunflower, crochet daisy, crochet spiderman, crochet penguin, crochet turtle, crochet scarf, crochet blanket, crochet minion, crochet pouch]" --alt="Instagram Post" --allow-root
wp media import /data/media/videos/video_3911111365206993493.mp4 --title="Video 3911111365206993493" --caption="Crochet Tulip Flower 🌷✨🤌 DM To Order❤️  #crochet #crochettulip #amigurimi #crochetflower #crochetbusiness   [crochet butterfly, crochet tulip, crochet tulip flower, crochet clover, crochet rose, crochet flowers, crochet plushie, crochet sunflower, crochet daisy, crochet spiderman, crochet penguin, crochet turtle, crochet scarf, crochet blanket, crochet minion, crochet pouch]" --allow-root
wp media import /data/media/photos/post_3909847960370099027.jpg --title="Post 3909847960370099027" --caption="Crochet Butterfly✨🦋 DM To Order❤️  #crochet #crochetbutterfly #amigurimi #crochetkeychain #crochetbusiness   [crochet butterfly, crochet clover, crochet rose, crochet flowers, crochet plushie, crochet sunflower, crochet daisy, crochet spiderman, crochet penguin, crochet turtle, crochet scarf, crochet blanket, crochet minion, crochet pouch]" --alt="Instagram Post" --allow-root
wp media import /data/media/videos/video_3909847960370099027.mp4 --title="Video 3909847960370099027" --caption="Crochet Butterfly✨🦋 DM To Order❤️  #crochet #crochetbutterfly #amigurimi #crochetkeychain #crochetbusiness   [crochet butterfly, crochet clover, crochet rose, crochet flowers, crochet plushie, crochet sunflower, crochet daisy, crochet spiderman, crochet penguin, crochet turtle, crochet scarf, crochet blanket, crochet minion, crochet pouch]" --allow-root
wp media import /data/media/photos/post_3908313468572590167.jpg --title="Post 3908313468572590167" --caption="Crochet Butterfly 🦋 DM To Order❤️  #crochet #crochetbutterfly #amigurimi #crochetkeychain #crochetbusiness   [crochet butterfly, crochet clover, crochet rose, crochet flowers, crochet plushie, crochet sunflower, crochet daisy, crochet spiderman, crochet penguin, crochet turtle, crochet scarf, crochet blanket, crochet minion, crochet pouch]" --alt="Instagram Post" --allow-root
wp media import /data/media/videos/video_3908313468572590167.mp4 --title="Video 3908313468572590167" --caption="Crochet Butterfly 🦋 DM To Order❤️  #crochet #crochetbutterfly #amigurimi #crochetkeychain #crochetbusiness   [crochet butterfly, crochet clover, crochet rose, crochet flowers, crochet plushie, crochet sunflower, crochet daisy, crochet spiderman, crochet penguin, crochet turtle, crochet scarf, crochet blanket, crochet minion, crochet pouch]" --allow-root
wp media import /data/media/photos/post_3907090215950711773.jpg --title="Post 3907090215950711773" --caption="Crochet 4 leaf clover🍀 DM To Order❤️  #crochet #crochetclover #amigurimi #crochetkeychain #crochetbusiness   [crochet clover, crochet rose, crochet flowers, crochet plushie, crochet sunflower, crochet daisy, crochet spiderman, crochet penguin, crochet turtle, crochet scarf, crochet blanket, crochet minion, crochet pouch]" --alt="Instagram Post" --allow-root
wp media import /data/media/videos/video_3907090215950711773.mp4 --title="Video 3907090215950711773" --caption="Crochet 4 leaf clover🍀 DM To Order❤️  #crochet #crochetclover #amigurimi #crochetkeychain #crochetbusiness   [crochet clover, crochet rose, crochet flowers, crochet plushie, crochet sunflower, crochet daisy, crochet spiderman, crochet penguin, crochet turtle, crochet scarf, crochet blanket, crochet minion, crochet pouch]" --allow-root
wp media import /data/media/photos/post_3901972354043238158.jpg --title="Post 3901972354043238158" --caption="Crochet 🫶💞 DM To Order❤️  #crochet #crochetplushies #crochetbutterfly #crochetkeychain #crochetbusiness" --alt="Instagram Post" --allow-root
wp media import /data/media/videos/video_3901972354043238158.mp4 --title="Video 3901972354043238158" --caption="Crochet 🫶💞 DM To Order❤️  #crochet #crochetplushies #crochetbutterfly #crochetkeychain #crochetbusiness" --allow-root
wp media import /data/media/photos/post_3901375958918309344.jpg --title="Post 3901375958918309344" --caption="Crochet Mini Kitty pouch 🧶✨ DM TO ORDER 💌   Shipping charges 60/- pan india   Cash on delivery not available   ❌No Bargain ❌  #crochet #crochetpouch #crochetkittypouch #phonecharms  charms crochetpattern #crochetkeychain  womeninbusiness amigurumi crochetamigurumi crochetroseblanket crochethairaccessories crochetsunflower, crochetdaisy" --alt="Instagram Post" --allow-root
wp media import /data/media/photos/post_3901375958918309344_0.jpg --title="Post 3901375958918309344 - 0" --caption="Crochet Mini Kitty pouch 🧶✨ DM TO ORDER 💌   Shipping charges 60/- pan india   Cash on delivery not available   ❌No Bargain ❌  #crochet #crochetpouch #crochetkittypouch #phonecharms  charms crochetpattern #crochetkeychain  womeninbusiness amigurumi crochetamigurumi crochetroseblanket crochethairaccessories crochetsunflower, crochetdaisy" --alt="Instagram Post" --allow-root
wp media import /data/media/photos/post_3901375958918309344_1.jpg --title="Post 3901375958918309344 - 1" --caption="Crochet Mini Kitty pouch 🧶✨ DM TO ORDER 💌   Shipping charges 60/- pan india   Cash on delivery not available   ❌No Bargain ❌  #crochet #crochetpouch #crochetkittypouch #phonecharms  charms crochetpattern #crochetkeychain  womeninbusiness amigurumi crochetamigurumi crochetroseblanket crochethairaccessories crochetsunflower, crochetdaisy" --alt="Instagram Post" --allow-root
wp media import /data/media/photos/post_3901080575504838179.jpg --title="Post 3901080575504838179" --caption="Crochet keychains 🫶✨DM TO ORDER ❤️  Standard shipping charges 60/-  Cash on delivery not available. Only prepaid orders accepted 🤌  ❌ NO BARGAIN ❌  #crochetplushie #phonecharms #crochetkeychain #amigrumi #smallbusiness" --alt="Instagram Post" --allow-root
wp media import /data/media/videos/video_3901080575504838179.mp4 --title="Video 3901080575504838179" --caption="Crochet keychains 🫶✨DM TO ORDER ❤️  Standard shipping charges 60/-  Cash on delivery not available. Only prepaid orders accepted 🤌  ❌ NO BARGAIN ❌  #crochetplushie #phonecharms #crochetkeychain #amigrumi #smallbusiness" --allow-root
wp media import /data/media/photos/post_3901061065642844125.jpg --title="Post 3901061065642844125" --caption="Packing Order ✨  Phone Charms, Anti Tarnish Jewelry, crochet keychains & more✨🎀🤌   DM TO ORDER 💌   Shipping charges 60/- pan india  Cash on delivery not available   ❌NO BARGAIN ❌   .  .  #phonecharmsindia #charms #crochet #hyderabad #crochetkeychains" --alt="Instagram Post" --allow-root
wp media import /data/media/videos/video_3901061065642844125.mp4 --title="Video 3901061065642844125" --caption="Packing Order ✨  Phone Charms, Anti Tarnish Jewelry, crochet keychains & more✨🎀🤌   DM TO ORDER 💌   Shipping charges 60/- pan india  Cash on delivery not available   ❌NO BARGAIN ❌   .  .  #phonecharmsindia #charms #crochet #hyderabad #crochetkeychains" --allow-root
